//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBlogStrapMVC5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int ID { get; set; }
        public int PostID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string Author { get; set; }
        public string CommentContent { get; set; }
        public string PublishDate { get; set; }
        public string AuthorURL { get; set; }
        public bool IsPublished { get; set; }
    
        public virtual Post Post { get; set; }
    }
}
