//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBlogStrapMVC5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.Comments = new HashSet<Comment>();
            this.PostsTags = new HashSet<PostsTag>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string PostContent { get; set; }
        public string Thumbnail { get; set; }
        public string PublishDate { get; set; }
        public string Author { get; set; }
        public bool IsPublished { get; set; }
        public bool AllowComments { get; set; }
        public string LastEdit { get; set; }
        public Nullable<long> Views { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<PostsTag> PostsTags { get; set; }
    }
}
