//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBlogStrapMVC5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public Tag()
        {
            this.PostsTags = new HashSet<PostsTag>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public bool IsTag { get; set; }
        public bool IsCategory { get; set; }
    
        public virtual ICollection<PostsTag> PostsTags { get; set; }
    }
}
